title: Music/Tech/Culture
author: chrsam
email: mananghayac@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The world around us is constantly changing. The gap between 
  generations is evident in the things that matter to each group.
  This blog is a collection of thoughts on talking points of
  today's young adults - those may not know their future, but 
  want to make the most of the present. 

# social links
twitter_username: @chrs_man
github_username:  @chrsam

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
